# https://heroiclabs.com/docs/nakama/server-framework/server-configuration/
name: nakama1
socket:
  server_key: nakama_godot4_extended
database:
  address:
    - "postgres:localdb@postgres:5432/nakama"
logger:
  level: DEBUG
session:
  token_expiry_sec: 7200
console:
  username: nakama
  password: password123
runtime:
  path: /nakama/modules
